const API='https://fvttsguxeocisqvcrbqh.supabase.co/functions/v1/jstech-prime-public-api';
const WHATSAPP='5527997314781';
const fallback=[{source_key:'plenocs',name:'Pleno CS',plans:[{name:'Mensal',price:20,months:1,service:'CS Satélite'},{name:'Trimestral',price:55,months:3,service:'CS Satélite'},{name:'Semestral',price:100,months:6,service:'CS Satélite'},{name:'Anual',price:150,months:12,service:'CS Satélite'},{name:'Mensal',price:20,months:1,service:'CS NET'},{name:'Mensal',price:25,months:1,service:'IPTV'},{name:'Trimestral',price:65,months:3,service:'IPTV'},{name:'Semestral',price:120,months:6,service:'IPTV'},{name:'Anual',price:210,months:12,service:'IPTV'}],compatibility:['Smart TV','TV Box','Celular','Computador']},{source_key:'questbr',name:'Quest BR',plans:[{name:'Mensal',price:25,months:1,service:'IPTV'},{name:'Trimestral',price:65,months:3,service:'IPTV'},{name:'Semestral',price:130,months:6,service:'IPTV'},{name:'Anual',price:250,months:12,service:'IPTV'}],compatibility:['Android TV','Fire TV Stick','Chromecast','Roku','Android','iPhone','Notebook','PC','iPad','Apple TV']},{source_key:'camisa10',name:'Camarote Camisa 10',plans:[{name:'Mensal',price:30,months:1,service:'IPTV'},{name:'Trimestral',price:80,months:3,service:'IPTV'},{name:'Semestral',price:150,months:6,service:'IPTV'},{name:'Anual',price:280,months:12,service:'IPTV'}],compatibility:['Smart TV','TV Box','Fire TV Stick','Celular','Tablet','Computador']}];
let sources=fallback,csService='CS Satélite',iptvSource='plenocs';
const money=v=>Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const uniq=a=>[...new Set(a.filter(Boolean))];
const wa=text=>`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(text)}`;

function wireWhatsApp(){document.querySelectorAll('[data-wa]').forEach(el=>{let text='Olá! Vim pelo site da JSTech Prime e gostaria de conhecer os serviços.';if(el.dataset.wa==='trial')text='Olá! Vim pelo site da JSTech Prime e gostaria de solicitar um teste.';if(el.dataset.wa==='cs-trial')text='Olá! Vim pelo site da JSTech Prime e quero solicitar um teste de CS. Meu receptor é: ';if(el.dataset.wa==='iptv-trial')text='Olá! Vim pelo site da JSTech Prime e quero solicitar um teste de IPTV. Meu aparelho é: ';if(el.dataset.wa==='support')text='Olá! Vim pelo site da JSTech Prime e preciso de ajuda para escolher entre CS e IPTV.';el.href=wa(text);el.target='_blank';el.rel='noopener noreferrer'})}
function sourceName(source){return source?.name||({plenocs:'Opção 1',questbr:'Opção 2',camisa10:'Opção 3'}[source?.source_key]||'IPTV')}
function plansFor(service,sourceKey){const all=sourceKey?sources.find(s=>s.source_key===sourceKey)?.plans||[]:sources.flatMap(s=>s.plans||[]);return all.filter(p=>(p.service||'IPTV')===service).sort((a,b)=>(a.months||1)-(b.months||1))}
function planCards(plans,kind,label){if(!plans.length)return'<div class="plan"><h3>Atualizando planos…</h3><p>O último catálogo válido será carregado em instantes.</p></div>';const max=Math.max(...plans.map(p=>Number(p.months)||1));return plans.map(p=>{const months=Number(p.months)||1,featured=months===max&&plans.length>1,eq=p.monthly_equivalent||Number(p.price)/months;const msg=`Olá! Vim pelo site da JSTech Prime e quero ${label}, plano ${p.name}, por R$ ${money(p.price)}.`;return `<article class="plan ${featured?'featured':''}"><small class="tag">${featured?'MELHOR CUSTO':months===1?'PARA COMEÇAR':'ECONOMIZE MAIS'}</small><h3>${p.name}</h3><div class="price"><span>R$</span><b>${money(p.price)}</b></div><div class="equivalent">${months>1?`equivale a R$ ${money(eq)} por mês`:'pagamento mensal'}</div><ul><li>Teste quando disponível</li><li>Ativação rápida</li><li>Suporte pelo WhatsApp</li><li>Sem fidelidade obrigatória</li></ul><a class="button ${kind==='cs'?'cs-button':'iptv-button'}" href="${wa(msg)}" target="_blank">ESCOLHER PLANO →</a></article>`}).join('')}
function renderCS(){const tabs=document.getElementById('csTabs');tabs.innerHTML=['CS Satélite','CS NET'].map(s=>`<button class="${s===csService?'active':''}" data-service="${s}">${s}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{csService=b.dataset.service;renderCS()});document.getElementById('csPlans').innerHTML=planCards(plansFor(csService),'cs',csService)}
function renderIPTV(){const available=sources.filter(s=>(s.plans||[]).some(p=>(p.service||'IPTV')==='IPTV'));if(!available.some(s=>s.source_key===iptvSource))iptvSource=available[0]?.source_key;const tabs=document.getElementById('iptvTabs');tabs.innerHTML=available.map(s=>`<button class="${s.source_key===iptvSource?'active':''}" data-source="${s.source_key}">${sourceName(s)}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{iptvSource=b.dataset.source;renderIPTV()});const source=available.find(s=>s.source_key===iptvSource);document.getElementById('iptvPlans').innerHTML=planCards(plansFor('IPTV',iptvSource),'iptv',`IPTV ${sourceName(source)}`)}
function renderDevices(){const devices=uniq(sources.flatMap(s=>s.compatibility||[]));const icons=['📺','▣','▯','⌨','◫','◇'];document.getElementById('deviceList').innerHTML=devices.slice(0,12).map((d,i)=>`<article>${icons[i%icons.length]}<b>${d}</b></article>`).join('');const dates=sources.map(s=>new Date(s.fetched_at||0)).filter(d=>d.getTime()>0);if(dates.length)document.getElementById('lastUpdate').textContent='Atualizado: '+new Date(Math.max(...dates)).toLocaleString('pt-BR')}
async function load(){try{const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw 0;const p=await r.json();if(Array.isArray(p.sources)&&p.sources.length)sources=p.sources}catch(e){console.warn('Catálogo de segurança ativo')}renderCS();renderIPTV();renderDevices()}
document.querySelectorAll('.faq button').forEach(btn=>btn.onclick=()=>{const item=btn.closest('.faq'),open=item.classList.contains('open');document.querySelectorAll('.faq.open').forEach(x=>x.classList.remove('open'));if(!open)item.classList.add('open')});
const form=document.getElementById('leadForm');form?.addEventListener('submit',async e=>{e.preventDefault();const status=document.getElementById('formStatus'),button=form.querySelector('button');const data=Object.fromEntries(new FormData(form).entries());if(String(data.nome||'').trim().length<2||String(data.whatsapp||'').replace(/\D/g,'').length<8||!data.servico){status.textContent='Preencha nome, WhatsApp e serviço.';return}button.disabled=true;button.textContent='ENVIANDO…';try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw 0;status.textContent='Solicitação enviada com sucesso!';form.reset()}catch{status.textContent='Não foi possível enviar. Use o WhatsApp.'}finally{button.disabled=false;button.textContent='ENVIAR SOLICITAÇÃO →'}});
wireWhatsApp();load();
